---
- hosts: localhost
  gather_facts: no
  become: yes

  vars:
    image_name: "chicheto94/upskilldevopscourse"
    image_tag: "v0.1"
    listen_port: "5001"

  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: "/home/rosen_minchev/devops-programme"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build

    - name: Push Docker image to registry
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    - name: Run the Docker container
      community.docker.docker_container:
        name: "python-app-container"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ listen_port }}:{{ listen_port }}"
        env:
          PORT: "{{ listen_port }}"
