name: GitHub Practice

on: [push]


jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  check_markdown_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          config: markdownlint.json
          files: '**/*.md'
          ignore: node_modules

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') || true

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black app/

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.13'
      - name: Test
        uses: onichandame/python-test-action@master

  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan for secrets
        uses: zricethezav/gitleaks-action@v1

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Snyk Security Scan
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [editorconfig, check_markdown_files, lint, unittest, check_secrets, sast, sca]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub

        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: chicheto94/upskilldevopscourse:${{ github.sha }}

  scan_docker_image:
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - uses: actions/checkout@v2
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'chicheto94/upskilldevopscourse:${{ github.sha }}'

